imu0: /imu/data_raw
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              true, false, false]

imu0_differential: true
imu0_relative: false

imu0_remove_gravitational_acceleration: true