#!/usr/bin/env bash

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
REPO_DIR=`readlink -f ${SCRIPTS_DIR}/..`

xacro --inorder ${REPO_DIR}/urdf/lubobot.urdf.xacro > ${REPO_DIR}/lubobot.urdf
