#!/usr/bin/env python

from geometry_msgs.msg import Twist
import rospy
import time


def callback(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)


def move_robot_test():
    rospy.init_node('move_robot_test', anonymous=True)
    twist_pub = rospy.Publisher("cmd_vel", Twist, queue_size=10)
    rate = rospy.Rate(10)  # 10hz
    t_end = time.time() + 5 # 5 seconds after
    rospy.loginfo("Moving robot...")

    while time.time() < t_end:
        twist_msg = Twist()
        twist_msg.linear.x = 0.1 # 0.1 m / s
        twist_pub.publish(twist_msg)
        rate.sleep()
    rospy.loginfo("Finished!")


if __name__ == '__main__':
    try:
        move_robot_test()
    except rospy.ROSInterruptException:
        pass
