imu_publisher:
  topic_name: "imu_data"
  frame_id: "imu_link"
  i2c_bus: 1
  device_address: 0x68
  x_accel_offset: 0
  y_accel_offset: 0
  z_accel_offset: 0
  x_gyro_offset: 0
  y_gyro_offset: 0
  z_gyro_offset: 0
