imu_publisher:
  topic_name: "imu_data"
  frame_id: "imu_link"
  i2c_bus: 1
  device_address: 0x68
  x_accel_offset: -512
  y_accel_offset: -2263
  z_accel_offset: 1893
  x_gyro_offset: 29
  y_gyro_offset: -56
  z_gyro_offset: 74
