imu_publisher:
  topic_name: "imu_data"
  frame_id: "imu_link"
  i2c_bus: 1
  device_address: 0x68
  x_accel_offset: -427
  y_accel_offset: -2187
  z_accel_offset: 1895
  x_gyro_offset: 47
  y_gyro_offset: -46
  z_gyro_offset: 75
